baseURL = "https://lord-rapture.github.io"
languageCode = "en-us"
title = "Lord Rapture"
theme = "github-style"
publishDir = "docs"
googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  contributions = "post"
  author = "Lord Rapture"
  github = "Elliott Buckingham"
  description = "</head><body>"
  twitter = "LordRapture"
  email = "L.Rapture@protonmail.com"
  url = "https://lord-rapture.github.io"
  keywords = "blog, google analytics"
  rss = false
  location = "Birmingham, UK"
  lastmod = true
  avatar = "https://github.com/Lord-Rapture/lord-rapture.Github.io/blob/main/resources/_gen/images/avatar.png?raw=true"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]